# Generated by Django 2.1.3 on 2018-11-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederalSupplyClassification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'federal_supply_classification',
            },
        ),
        migrations.CreateModel(
            name='FederalSupplyGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'federal_supply_group',
            },
        ),
    ]
